kind: T_Collection
operations:
- id: OP_READ
  effects: []
  forbidden_outputs:
  - Updated Memory State
  inputs:
  - Memory State
  - Query
  name: READ
  outputs:
  - Memory Vector
  owner: Associative Memory
- id: OP_UPDATE
  effects:
  - modifies Memory State
  forbidden_outputs:
  - Memory Vector
  implicit_operations_forbidden:
  - READ
  inputs:
  - Memory State
  - Semantic Representation
  name: UPDATE
  outputs:
  - Updated Memory State
  owner: Associative Memory
pipeline:
  id: PROC_SFL
  name: Semantic Feedback Learning Pipeline
  stages:
  - External Input
  - Associative Memory READ
  - Memory Vector
  - Transformer semantic reasoning
  - Transformer semantic teaching
  - Semantic Representation
  - Associative Memory UPDATE
  - Updated Memory State
